languageCode = "en"
languageName = "English"
weight = 1

title = "Vidhi Saini"

[params]
  description = "Vidhi Saini | CA Finalist"
  images = ['img/author.jpeg']
  title = "Vidhi Saini | CA Finalist"
  [params.social]
    linkedin = "https://www.linkedin.com/in/vidhi-saini-b32034319/"

[params.author]
bio = "CA Finalist"
headline = "CA Finalist"
image = "img/author.jpeg"
links = [
  { linkedin = 'https://www.linkedin.com/in/vidhi-saini-b32034319/' },
  { email = "mailto:vidhisaini2112@gmail.com" },
  { instagram = "https://www.instagram.com/vvi.tty/" },
]
name = "Vidhi Saini"
